### PR TITLE
Add AUR installation method to README.md

### PR DESCRIPTION
**Pull request by mkornat**

### CODE REVIEW

**Comment by j178** [comment]
Thanks for your PR!

This reminds that I can use `goreleaser` to update AUR package automatically on every release, so I created #272 to supersede this one, thanks again!

**Comment by mkornat** [comment]
You could adopt my package https://aur.archlinux.org/packages/leetgo if You
want.

pt., 26 sty 2024 o 20:21 Jo ***@***.***> napisał(a):

**Comment by j178** [comment]
Thanks, would you like to transfer that package to me (j178)?

**Comment by mkornat** [comment]
Sure, I transferred package to You.
BTW, app works great after the fix.
Thanks and take care.

sob., 27 sty 2024 o 06:27 Jo ***@***.***> napisał(a):

**Pull request closed without merging**
